### ISSUE TITLE
MissingPluginException: No implementation found for method listen on channel flutter_keyboard_visibility

### ISSUE THREAD

**Issue by jbarasa** [EchoEllet/flutter_keyboard_visibility_temp_fork#4]
**Describe the bug**
The package flutter_keyboard_visibility_temp_fork throws a MissingPluginException when attempting to use the KeyboardVisibilityBuilder widget. The error indicates that no implementation was found for the method 'listen' on the flutter_keyboard_visibility channel.

**Expected behavior**
The KeyboardVisibilityBuilder should properly detect keyboard visibility changes and rebuild the widget accordingly without throwing any exceptions.

 
**Additional context**

- The issue appears to be related to missing platform-specific implementations in the forked package
- The official flutter_keyboard_visibility package (v6.0.0) works correctly with the same implementation

**To Reproduce**
1. Add flutter_keyboard_visibility_temp_fork: ^0.1.4 to pubspec.yaml
2.Import the package in a Flutter widget:

```
import 'package:flutter_keyboard_visibility_temp_fork/flutter_keyboard_visibility_temp_fork.dart';

```

3. Use the KeyboardVisibilityBuilder in a widget:
```
KeyboardVisibilityBuilder(
  builder: (context, isKeyboardVisible) {
    // Widget code here
  }
)

```
4. Run the app
5. The exception is thrown immediately when the widget is rendered

**Info (please complete the following information):**
flutter_keyboard_visibility_temp_fork version: 0.1.4
Reproducible on platforms: Android
Flutter version: 3.24.5
Error stack trace:
```
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel flutter_keyboard_visibility:
MissingPluginException(No implementation found for method listen on channel flutter_keyboard_visibility)

Stack trace:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:676:9)

```

**Comment by EchoEllet** [comment]
> The KeyboardVisibilityBuilder should properly detect keyboard visibility changes and rebuild the widget accordingly without throwing any exceptions.

I tested it with the example and it seems to work as expected. 

* Are you using both [flutter_keyboard_visibility](https://pub.dev/packages/flutter_keyboard_visibility) and [flutter_keyboard_visibility_temp_fork](https://pub.dev/packages/flutter_keyboard_visibility_temp_fork) in the same project? Both use the same method channel name `flutter_keyboard_visibility` since both depend on [flutter_keyboard_visibility_platform_interface](https://pub.dev/packages/flutter_keyboard_visibility_platform_interface).
* Can you test the example app:

```shell
$ git clone --depth 1 https://github.com/EchoEllet/flutter_keyboard_visibility_temp_fork.git
$ (cd flutter_keyboard_visibility_temp_fork/flutter_keyboard_visibility_temp_fork/example && flutter run)
```

<img src="https://github.com/user-attachments/assets/e82d366f-846d-4a11-8e1e-5b0abf7df1da" alt="The plugin is working in Android, tested on Api 28 and 34" width="300" />

**Comment by jbarasa** [comment]
Your example works fine I guess the error is produced with riverpod I will try a different method and share outcome.

**Comment by EchoEllet** [comment]
> I guess the error is produced with riverpod I will try a different method and share outcome.

Riverpod is not related to the error output you shared, could you confirm if you're using both the original and the fork packages with the same project?

**Comment by jbarasa** [comment]
No i am using the fork package only with Riverpod's Provider as a state manager

**Comment by EchoEllet** [comment]
Can you share `pubspec.lock`? Just to ensure it's not a transitive dependency.

**Comment by jbarasa** [comment]
> Can you share `pubspec.lock`? Just to ensure it's not a transitive dependency.

I kinda had to re-write a lot of code with flutter bloc but as soon as i re-install the package, i will share any issues encountered with the "flutter_keyboard_visibility_temp_fork" package . Thanks

**Comment by EchoEllet** [comment]
> bloc but as soon as i re-install the package, i will share any issues encountered with the

The two commands above are minimal to run. Once you confirm the issue, you can remove the directory `flutter_keyboard_visibility_temp_fork`.

I need a mininal reproducible example. If this issue is the fork conflicting with the original package, it's possible to solve it.

The `pubspec.lock` is where the transitive dependencies are stored.
